//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModuleEntitiy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_HSCode
    {
        public int Id { get; set; }
        public string HSCode { get; set; }
        public string Description { get; set; }
        public decimal CD { get; set; }
        public decimal SD { get; set; }
        public decimal VAT { get; set; }
        public decimal AIT { get; set; }
        public decimal RD { get; set; }
        public decimal AT { get; set; }
        public decimal TTL { get; set; }
    }
}
