//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModuleEntitiy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Product
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int ProductGroup { get; set; }
        public int ProductType { get; set; }
        public int MeasurementUnit { get; set; }
        public decimal Rate { get; set; }
        public decimal ROL { get; set; }
        public System.DateTime ExpieryDate { get; set; }
        public decimal SD { get; set; }
        public decimal VAT { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ModifierId { get; set; }
        public System.DateTime ModificationDate { get; set; }
    }
}
