//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModuleEntitiy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_ProductCodeIntegration
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string HSCode { get; set; }
        public string AccountsCode { get; set; }
        public byte[] Barcode { get; set; }
    }
}
