//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModuleEntitiy.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class security_modulesEntities : DbContext
    {
        public security_modulesEntities()
            : base("name=security_modulesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AD_BusinessNature> AD_BusinessNature { get; set; }
        public virtual DbSet<AD_BusinessType> AD_BusinessType { get; set; }
        public virtual DbSet<AD_CompanyProfile> AD_CompanyProfile { get; set; }
        public virtual DbSet<AD_Bank> AD_Bank { get; set; }
        public virtual DbSet<AD_Customer> AD_Customer { get; set; }
        public virtual DbSet<AD_ExpenseHead> AD_ExpenseHead { get; set; }
        public virtual DbSet<AD_HSCode> AD_HSCode { get; set; }
        public virtual DbSet<AD_MeasurementUnit> AD_MeasurementUnit { get; set; }
        public virtual DbSet<AD_PaymentMethod> AD_PaymentMethod { get; set; }
        public virtual DbSet<AD_PricingType> AD_PricingType { get; set; }
        public virtual DbSet<AD_ProductGroup> AD_ProductGroup { get; set; }
        public virtual DbSet<AD_ProductType> AD_ProductType { get; set; }
        public virtual DbSet<AD_Purpose> AD_Purpose { get; set; }
        public virtual DbSet<AD_Reason> AD_Reason { get; set; }
        public virtual DbSet<AD_SalesOutlet> AD_SalesOutlet { get; set; }
        public virtual DbSet<AD_Store> AD_Store { get; set; }
        public virtual DbSet<AD_StoreItemStatusDeclaration> AD_StoreItemStatusDeclaration { get; set; }
        public virtual DbSet<AD_Supplier> AD_Supplier { get; set; }
        public virtual DbSet<AD_Terminal> AD_Terminal { get; set; }
        public virtual DbSet<AD_Product> AD_Product { get; set; }
        public virtual DbSet<AD_ProductCodeIntegration> AD_ProductCodeIntegration { get; set; }
        public virtual DbSet<AD_ProductPricing> AD_ProductPricing { get; set; }
    }
}
