//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminModuleEntitiy.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class security_modulesEntities : DbContext
    {
        public security_modulesEntities()
            : base("name=security_modulesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AD_BusinessNature> AD_BusinessNature { get; set; }
        public virtual DbSet<AD_BusinessType> AD_BusinessType { get; set; }
        public virtual DbSet<AD_CompanyProfile> AD_CompanyProfile { get; set; }
    }
}
